export const catalouges = [
  {
    _id: "1",
    title: "Treadmill",
    content: `A treadmill is a device generally used for walking, running, or climbing while staying in the same place.`,
    url: `https://hips.hearstapps.com/ame-prod-menshealth-assets.s3.amazonaws.com/main/assets/treadmill.gif`,
    calories: 10,
  },
  {
    _id: "2",
    title: "Push Up",
    content: `The push-up (sometimes called a press-up in British English) is a common calisthenics exercise beginning from the prone position. By raising and lowering the body using the arms, push-ups exercise the pectoral muscles, triceps, and anterior deltoids, with ancillary benefits to the rest of the deltoids, serratus anterior, coracobrachialis and the midsection as a whole.`,
    url: "https://thumbs.gfycat.com/GlossySkinnyDuckbillcat-max-1mb.gif",
    calories: 10,
  },
  {
    _id: "3",
    title: "Sit Up",
    content: `The sit-up (or curl-up) is an abdominal endurance training exercise to strengthen, tighten and tone the abdominal muscles. It is similar to a crunch (crunches target the rectus abdominis and also work the external and internal obliques), but sit-ups have a fuller range of motion and condition additional muscles.`,
    url: "https://hips.hearstapps.com/hmg-prod/images/workouts/2016/08/situptwisting-1472152218.gif",
    calories: 10,
  },
  {
    _id: "4",
    title: "Burpee",
    content: `The burpee, a squat thrust with an additional stand between repetitions, is a full body exercise used in strength training. The movement itself is primarily an anaerobic exercise, but when done in succession over a longer period can be utilized as an aerobic exercise.`,
    url: "https://media.tenor.com/u2-VJiigKCkAAAAC/exercise-jump.gif",
    calories: 10,
  },
  {
    _id: "5",
    title: "Plank",
    content: `The plank (also called a front hold, hover, or abdominal bridge) is an isometric core strength exercise that involves maintaining a position similar to a push-up for the maximum possible time.`,
    url: "https://hips.hearstapps.com/hmg-prod/images/workouts/2016/03/plank-1457045584.gif",
    calories: 10,
  },
  {
    _id: "6",
    title: "Mountain Climber",
    content: `The mountain climber is typically considered an exercise to target your ab muscles. That's because you set up in a high plank (pushup) position, which challenges you to brace your core.`,
    url: "https://hips.hearstapps.com/hmg-prod/images/workouts/2016/08/mountainclimber-1472061303.gif",
    calories: 10,
  },
  {
    _id: "7",
    title: "Jumping Jack",
    content: `A jumping jack, also known as a star jump and called a side-straddle hop in the US military, is a physical jumping exercise performed by jumping to a position with the legs spread wide and the hands going overhead, sometimes in a clap, and then returning to a position with the feet together and the arms at the sides.`,
    url: "https://www.icegif.com/wp-content/uploads/jumping-jacks-icegif-5.gif",
    calories: 10,
  },
  {
    _id: "8",
    title: "Squat",
    content: `A squat is a strength exercise in which the trainee lowers their hips from a standing position and then stands back up. During the descent of a squat, the hip and knee joints flex while the ankle joint dorsiflexes; conversely the hip and knee joints extend and the ankle joint plantarflexes when standing up.`,
    url: "https://hips.hearstapps.com/ame-prod-menshealth-assets.s3.amazonaws.com/main/assets/bodyweight-squat.gif",
    calories: 10,
  },
  {
    _id: "9",
    title: "Lunge",
    content: `A lunge can refer to any position of the human body where one leg is positioned forward with knee bent and foot flat on the ground while the other leg is positioned behind. It is used by athletes in cross-training for sports, by weight-trainers as a fitness exercise, and by practitioners of yoga as part of an asana regimen.`,
    url: "https://media.tenor.com/fWiC9Ze5eUMAAAAC/lunges-exercise.gif",
    calories: 10,
  },
  {
    _id: "10",
    title: "Buglute Bridge",
    content: `The bridge (also called gymnastic bridge) is an exercise. Many variations of this exercise are employed throughout the world, most commonly the balancing of the body on the hands and the feet. It is intended to improve lower back and gluteus strength. Examples of bridging in sportive or self-defense applications are seen in Kung Fu, Judo, Brazilian jiu jitsu, Capoeira, mixed martial arts, and wrestling.`,
    url: "https://hips.hearstapps.com/hmg-prod/images/workouts/2016/08/glutebridgedynamic-1472218237.gif",
    calories: 10,
  },
  {
    _id: "11",
    title: "Slide Lunge",
    content: `Bend your right leg while sliding the left foot backward into a lunge position. Keep the front knee behind the toe and keep the back leg slightly bent. Also keep the weight in the front leg so you always have control of the foot resting on the plate.`,
    url: "https://media.tenor.com/DwuD868X1OUAAAAC/side-lunge.gif",
    calories: 10,
  },
  {
    _id: "12",
    title: "Biceps Curl",
    content: `The term "biceps curl" refers to any of a number of weight training exercises that primarily targets the biceps brachii muscle. It may be performed using a barbell, dumbbell, resistance band, or other equipment.`,
    url: "https://thumbs.gfycat.com/SlushyMetallicAtlanticsharpnosepuffer-size_restricted.gif",
    calories: 10,
  },
];

